# Perfil de desarrollo (activo por defecto): valores locales y secreto JWT solo para desarrollo
jwt.secret=${JWT_SECRET:615da61a80ef2c5c635552296cf94fa10173624dd996d010f4a8777e128dda83}
spring.jpa.show-sql=${SHOW_SQL:false}
